sudo: required
services:
  - docker

before_install:
  - docker build -t damianlis/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true damianlis/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-499974957004'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key: '$AWS_SECRET_KEY'
